'use client'

import { useState } from 'react'
import { usePathname, useRouter } from 'next/navigation'
import {
  Bell, BookOpen, Camera as CameraIcon, Check, ChevronDown, ChevronRight, CircleHelp,
  Clock3, FileText, Home, LockKeyhole, Menu, Play, Printer, RotateCcw,
  ScanLine, Share2, Sparkles, Star, TrendingUp, UserRound, X, Zap,
} from 'lucide-react'

const teal = '#2f7168'
const lessons = [
  { week: 'Week 4', title: '第十课 - 我们的校园', pinyin: 'wǒ men de xiào yuán', words: [['校园','xiào yuán'],['操场','cāo chǎng'],['老师','lǎo shī'],['礼堂','lǐ táng']], status: 'Pending Practice', tone: 'amber' },
  { week: 'Week 3', title: '第九课 - 我爱我的家', pinyin: 'wǒ ài wǒ de jiā', words: [['爸爸','bà ba'],['妈妈','mā ma'],['温暖','wēn nuǎn']], status: 'Completed (80%)', tone: 'green' },
  { week: 'Week 2', title: '第八课 - 快乐的周末', pinyin: 'kuài lè de zhōu mò', words: [['玩耍','wán shuǎ'],['公园','gōng yuán']], status: 'Needs Revision', tone: 'red' },
]
const nav = [{href:'/', label:'Dashboard', icon:Home},{href:'/syllabus', label:'Syllabus', icon:BookOpen},{href:'/history', label:'History', icon:Clock3},{href:'/premium', label:'Premium', icon:Star}]

function AppShell({ children }: { children: React.ReactNode }) {
  const path = usePathname(); const router = useRouter()
  return <div className="app-shell">
    <header className="topbar"><div className="brand-mark">S</div><div className="welcome"><span>Welcome back,</span><strong>Sarah</strong></div><button className="class-pill">Lucas – Primary 2 <ChevronDown size={13}/></button><button className="icon-btn"><Bell size={18}/></button></header>
    <main className="main-content">{children}</main>
    <nav className="bottom-nav">{nav.map(({href,label,icon:Icon})=><button key={href} onClick={()=>router.push(href)} className={path===href?'active':''}><Icon size={19}/><span>{label}</span></button>)}</nav>
  </div>
}

function ProgressCard(){return <section className="credit-card"><div className="card-top"><div><span className="eyebrow">PREPAID LESSON CREDITS</span><div className="credit-number">12 <small>of 20 Remaining</small></div></div><button className="dark-button">Top Up</button></div><div className="progress"><span style={{width:'60%'}}/></div><p>Credits expire on 30 Nov 2026</p></section>}
function Dashboard(){const router=useRouter(); return <><div className="section-heading"><div><p className="eyebrow">TUESDAY, 14 OCTOBER 2026</p><h1>Good afternoon, Sarah</h1></div><button className="help"><CircleHelp size={18}/></button></div><ProgressCard/><div className="stats-row"><div className="stat-card"><span>MASTERY RATE <TrendingUp size={14}/></span><strong>82.4%</strong><small>+3.1% this month</small></div><div className="stat-card"><span>PRACTICED <BookOpen size={14}/></span><strong>48 Characters</strong><small>8 lists covered</small></div></div><section><div className="row-heading"><h2>Upcoming Ting Xie</h2><button>View All <ChevronRight size={15}/></button></div><div className="date-strip">{['Mon|12','Tue|13','Wed|14','Thu|15','Fri|16','Sat|17'].map((d,i)=>{let [a,b]=d.split('|');return <div className={i===2?'selected':''} key={d}><small>{a}</small><strong>{b}</strong></div>})}</div><div className="upcoming"><div className="alarm"><Bell size={16}/></div><div><strong>Week 4: (第十课) Spelling Test</strong><p>Wednesday, 14 Oct at 3:00 PM · P2 MOE Syllabus</p></div></div></section><button className="scan-cta" onClick={()=>router.push('/camera')}><ScanLine size={18}/> Scan & Grade Worksheet</button></>}
function Syllabus(){const [tab,setTab]=useState('P2'); return <><div className="section-heading"><div><p className="eyebrow">MOE PRIMARY 2 SYLLABUS</p><h1>Chinese Syllabus</h1></div><button className="help"><Menu size={19}/></button></div><div className="tabs">{['P1','P2','P3','P4','P5','P6'].map(t=><button className={tab===t?'selected':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="row-heading syllabus-title"><h2>{tab} MOE Primary 2 Syllabus</h2><span>24 Lessons Total</span></div>{lessons.map((lesson)=><article className="lesson-card" key={lesson.week}><div className="lesson-header"><div><span className="eyebrow">{lesson.week}</span><h3>{lesson.title}</h3><p>{lesson.pinyin}</p></div><span className={'status '+lesson.tone}>{lesson.status}</span></div><div className="word-grid">{lesson.words.map(([cn,py])=><div key={cn}><strong>{cn}</strong><small>{py}</small></div>)}</div><button className="print-link"><Printer size={14}/> Print A4 Worksheet (PDF)<ChevronRight size={14}/></button></article>)}</>}
function Camera(){const router=useRouter(); const [capturing,setCapturing]=useState(false); return <div className="camera-page"><div className="camera-image"><div className="camera-top"><button onClick={()=>router.back()}><X size={18}/></button><span>Align Worksheet</span><button><Zap size={16}/></button></div><div className="brackets"><i/><i/><i/><i/></div><div className="camera-tip">Keep page flat and inside the brackets</div><button className="shutter" onClick={()=>{setCapturing(true);setTimeout(()=>router.push('/results'),900)}}><span>{capturing?'':' '}</span></button><div className="capture-label">{capturing?'Processing…':'Capture & Grade'}</div><div className="home-indicator"/></div></div>}
function Results(){const router=useRouter(); return <><div className="section-heading"><div><p className="eyebrow">TEST FEEDBACK</p><h1>Week 4 Syllabus Test</h1></div><span className="status red">Needs Revision</span></div><section className="score-card"><div className="score-ring">80%</div><div><strong>Score: 8/10</strong><small>Graded on 14 Oct, 3:12 PM</small><b>2 characters missed</b></div></section><h2 className="table-title">Results over time</h2><div className="results-table"><div className="table-row table-head"><span>Character</span><span>8 Oct</span><span>10 Oct</span><span>12 Oct</span></div>{[['操场','c','c','check'],['礼堂','x','x','x'],['校园','x','check','check'],['老师','check','check','check'],['同学','check','check','check'],['教室','x','check','check'],['图书馆','x','x','check'],['食堂','x','check','check'],['花园','x','check','check'],['运动场','x','x','check']].map(([word,...marks])=><div className="table-row" key={word}><span>{word}</span>{marks.map((m,i)=><span className={m==='check'?'correct':'wrong'} key={i}>{m==='check'?'✓':'×'}</span>)}</div>)}</div><div className="result-actions"><button className="soft-button"><Share2 size={15}/> Share Report</button><button className="dark-button" onClick={()=>router.push('/camera')}><RotateCcw size={15}/> Retest Missed</button></div></>}
function History(){return <><div className="section-heading"><div><p className="eyebrow">YOUR PRACTICE LOG</p><h1>History</h1></div><button className="help"><Menu size={19}/></button></div>{['Week 4 Syllabus Test','Week 3 Character Review','Week 2 Syllabus Test'].map((x,i)=><button className="history-item" key={x}><div className="history-icon">{i===0?<FileText size={17}/>:<Check size={17}/>}</div><div><strong>{x}</strong><small>{i===0?'14 Oct 2026 · 3:12 PM':'09 Oct 2026 · 4:20 PM'}</small></div><span>{i===0?'80%':'92%'}</span><ChevronRight size={16}/></button>)}</>}
function App(){const path=usePathname(); let content=path==='/syllabus'?<Syllabus/>:path==='/camera'?<Camera/>:path==='/results'?<Results/>:path==='/history'?<History/>:<Dashboard/>; return path==='/camera'?content:<AppShell>{content}</AppShell>}
export default App
